### ISSUE TITLE
indiana jones sandbag

### ISSUE THREAD

**Issue by adamrneary** [adamrneary/tactile#1]
you know the scene in raider's: http://www.youtube.com/watch?v=5a9NVDgKc4o

indiana has to swap out the idol with the sandbag without tripping the alarm. it doesn't work in the movie, but we need it to work for us. ;-)

...all jokes/metaphors aside...

the requirement is that we take the charting functionality out of the activecell repo and replace it with tactile.js without everything in the app breaking. plain and simple.

**Comment by lucassus** [comment]
I love this idea! ;)

**Comment by zmaril** [comment]
First baby steps have been taken: 
https://github.com/activecell/activecell/compare/herr_jones
![Screen Shot 2012-12-25 at 12 54 29 AM](https://f.cloud.github.com/assets/539927/30283/9ed74416-4e57-11e2-90f5-8166c7b4aac3.png)

**Comment by adamrneary** [comment]
This looks like conversion page. Show reach was a lot farther along--get
like we were just a few config changes away from perfection. Are you air we
need such a restart?

Sent by iPhone

On Dec 25, 2012, at 12:56 AM, Zack Maril notifications@github.com wrote:

First baby steps have been taken:
https://github.com/activecell/activecell/compare/herr_jones
[image: Screen Shot 2012-12-25 at 12 54 29
AM]https://f.cloud.github.com/assets/539927/30283/9ed74416-4e57-11e2-90f5-8166c7b4aac3.png

—
Reply to this email directly or view it on
GitHubhttps://github.com/activecell/tactile/issues/1#issuecomment-11669528.
