### ISSUE TITLE
other transitions

### ISSUE THREAD

**Issue by adamrneary** [adamrneary/tactile#146]
let's discuss if this is possible...

other transitions:
- [ ] leaderboard to stacked columns
- [ ] leaderboard to grouped columns
- [ ] leaderboard to lines
- [ ] leaderboard to pareto
- [ ] stacked columns to leaderboard
- [ ] stacked columns to lines
- [ ] stacked columns to pareto
- [ ] grouped columns to leaderboard
- [ ] grouped columns to lines
- [ ] grouped columns to pareto
- [ ] lines to stacked columns
- [ ] lines to grouped columns
- [ ] lines to leaderboard
- [ ] lines to pareto
- [ ] pareto to stacked columns
- [ ] pareto to grouped columns
- [ ] pareto to lines
- [ ] pareto to leaderboard

**Comment by adamrneary** [comment]
what i care about here most is object constancy. let's discuss how this is possible in each case.

**Comment by adamrneary** [comment]
simple slide down to remove and slide up to enter:
- [x] leaderboard to stacked columns
- [x] leaderboard to grouped columns
- [x] leaderboard to lines
- [x] leaderboard to pareto
- [x] stacked columns to leaderboard
- [x] grouped columns to leaderboard
- [x] lines to leaderboard
- [x] stacked columns to pareto
- [x] grouped columns to pareto
- [x] lines to pareto
- [x] pareto to leaderboard
- [x] pareto to stacked columns
- [x] pareto to grouped columns
- [x] pareto to lines

**Comment by adamrneary** [comment]
more sophisticated animations:
- [x] stacked columns to lines
- [x] grouped columns to lines
- [x] lines to stacked columns
- [x] lines to grouped columns

to animate away from lines, remove the line to the left, animate the node to the right location, then slide the columns up

to animate to lines, show the nodes, slide the columns down, animate the nodes to the right location, then animate the line from left to right.

**Comment by adamrneary** [comment]
@dunice-sergeym see comment above. this is not done.

**Comment by dunice-mezencev** [comment]
@adamrneary I update "pre_master_merge" branch. But coz we haven't specific _pareto_ renderer any chart with **line** will be animated as you describe.
- [x] from lines to any other: _remove the line to the left, animate the dots to the right, anything else - to bottom. Then call Show animation_
- [x] from any to lines: _slide lines from the left, slide dots from the right; slide up everything else_

It looks awesome ;-)

**Comment by adamrneary** [comment]
sorry, but i don't think it looks awesome. :-)

axes should animate only to adjust their own values, but not on and off screen. it looks really bad.
- [x] when series plotted on a cartesian plane (e.g. lines, columns, area, etc.) are going to disappear entirely, they should collapse up or down into the chart's baseline (where 0 appears on the y axis: http://cl.ly/image/0v1U3r0e4535)
- [x] if the first chart has axes and the second doesn't, the axes should disappear immediately after the series have collapsed into the baseline, and then the non-cartesian series (e.g. leaderboard) should animate in
- [x] if the first chart has no axes but the second does, the axes should disappear immediately after the non-cartesian series have disappeared, and then the cartesian series (e.g. columns) should animate in from the base line
- [x] most importantly, if both charts have axes, the axes should not disappear at all. they should only adjust as required as if the data changed.

**Comment by adamrneary** [comment]
next, on the index page, i am not seeing the different datasets being plotted. so when we transition from line to columns, for example, it's not clear why there's entirely different data. my goal was to animate between chart types and not to entirely remove one type and then add another type.

we aren't doing the "sophisticated" animations at all:
- [x] to animate away from lines, remove the line to the left, animate the node to the right location, then slide the columns up

this doesn't mean removing the nodes entirely. we're talking about keeping object constancy by actually animating the nodes as required to the correct location and then bringing columns up to them. right now there is no constancy because we're simply removing everything and then bringing in new stuff entirely.

let's add in the "area" type, and let's see the chart type transitions without blowing away the data in between each.

**Comment by dunice-mezencev** [comment]
> next, on the index page, i am not seeing the different datasets being plotted. so when we transition from line to columns, for example, it's not clear why there's entirely different data. my goal was to animate between chart types and not to entirely remove one type and then add another type.  

tactile lib created the way to add or create new series. So we can't just change one series (chart) to another.

**Comment by adamrneary** [comment]
accordingly to @dunice-sergeym this is not possible without a huge amount of rewrite, so we will abandon the desired outcome and just clean up what we have.

**Comment by adamrneary** [comment]
remaining cleanup for this:
- [x] animate series down to remove. animate series up to add (remove left to write stuff)
- [x] axes disappear and appear when removed/added or change type, but they animate when updated (currently they flash from one to the other)
- [x] there's a "blink" on update where the whole chart temporarily disappears during transition. let's kill that.

**Comment by dunice-mezencev** [comment]
Check out PR https://github.com/activecell/tactile/issues/146
All should work as described.

With best regards

2013/11/5 Adam Neary notifications@github.com
