### ISSUE TITLE
grunt not working properly (should be static)

### ISSUE THREAD

**Issue by adamrneary** [adamrneary/tactile#150]

**Comment by adamrneary** [comment]
- [x] annotated source page no longer working
- [ ] tests page no longer working

**Comment by dunice-mezencev** [comment]
To run test correctly any HttpServer should be used (due to file:// protocol restriction). testem.js and any other files are accessible at project root and unable to be loaded.
Use
- apache server
- python -m SimpleHTTPServer
- any other 

It makes file access and project loading much simplier

**Comment by adamrneary** [comment]
cool
