### ISSUE TITLE
coffeescript for examples

### ISSUE THREAD

**Issue by adamrneary** [adamrneary/tactile#16]
is it possible to convert the example files such as area.js into coffeescript without breaking the example pages? how much effort? two reasons:
1. since the chart interface is getting heavier with functions and tooltips and so on, these pages are getting complicated
2. we will be implementing the interface using coffeescript in the app, so it's closer to how we'll use it

what do you think?

**Comment by zmaril** [comment]
It is very possible to do this, probably take 10 minutes or so. 

While it makes sense for us to see the examples in coffeescript, if the eventual goal is to open source this project to the outside world with the hope of others using the library, I would caution against providing examples only in coffeescript though. 

Coffeescript "is just javascript" and, speaking from a personal perspective, it seems like the projects that crow on about how they are built with coffeescript come off as sophomoric, regardless of how good the software might be. At the point that they are using the compiled javascript you provide, no developer really cares what you built it with. 

It's easy for the guy who knows coffeescript to read javascript examples, but the same cannot be said for the javascript guy reading coffeescript examples. 

If we want other developers to use this library, I think the better choice would be to leave it in vanilla js as is. If we only want to use this internally, then we can do whatever we want and coffeescript is probably the right choice for the examples.

**Comment by adamrneary** [comment]
agreed. it was more for readability and our convenience than for the evangelical "preaching" factor, which always solicits such an eye-roll.

let's leave it as plain vanilla js for now, if only to avoid those eye-rolls and to leave it more open if we choose to open source.
