### ISSUE TITLE
revision to chart api

### ISSUE THREAD

**Issue by adamrneary** [adamrneary/tactile#26]
it really looks like we do need to stick with the original idea for a chainable api like mike bostock recommends (closures with getter/setter methods). see http://bost.ocks.org/mike/chart/

currently: 

``` javascript
var chart = new Tactile.Chart({
  element: $("#example_view")[0],
  width: 680,
  height: 400,
  data: data,
  axes: {
    x: {
      dimension: "time",
      frame: frameVal
    }
  },
  series: [
    {
      name: 'enemies',
      renderer: 'line',
      sigfigs: 0,
      draggable: true,
      afterDrag: function (d, y, i, draggedSeries, graph) {
        graph.data[i].y = y;
      },
      color: "#c05020",
      tooltip: function (d) {
        return d.y + " enemies";
      },
      dataTransform: function (d) {
        return {
          x: d.x,
          y: d.y
        };
      }
    },
    {
      name: 'friends',
      renderer: 'line',
      sigfigs: 1,
      color: "#6060c0",
      draggable: true,
      afterDrag: function (d, y, i, draggedSeries, graph) {
        graph.data[i].z = y;
      },
      tooltip: function (d) {
        return d.y + " friends";
      },
      dataTransform: function (d) {
        return {
          x: d.x,
          y: d.z
        };
      }
    }
  ]
});
```

should be something more like:

``` javascript
var chart = new Tactile.Chart()
  .element($("#example_view")[0])
  .width(680)
  .height(400)
  .data(data)
  .axes({
    x: {
      dimension: "time",
      frame: frameVal
    }
  })
  chart.series.push(
    {
      name: 'enemies',
      renderer: 'line',
      sigfigs: 0,
      draggable: true,
      afterDrag: function (d, y, i, draggedSeries, graph) {
        graph.data[i].y = y;
      },
      color: "#c05020",
      tooltip: function (d) {
        return d.y + " enemies";
      },
      dataTransform: function (d) {
        return {
          x: d.x,
          y: d.y
        };
      }
    });
  chart.series.push(
  {
      name: 'friends',
      renderer: 'line',
      sigfigs: 1,
      color: "#6060c0",
      draggable: true,
      afterDrag: function (d, y, i, draggedSeries, graph) {
        graph.data[i].z = y;
      },
      tooltip: function (d) {
        return d.y + " friends";
      },
      dataTransform: function (d) {
        return {
          x: d.x,
          y: d.z
        };
      }
    }
  );
```

**Comment by adamrneary** [comment]
the most immediate problem seems to be with this dichotomous nature of "renderers" as separate from series. when a chart is constructed it calls initrenderers(), which goes through the chart's series and adds a "renderer" for each series. i would think we could kill the concept of renderers and just convert them to series types or whatever. then, when the chart is rendered, rather than ignoring the array of series and looking to a parallel array of renderers, it could just go through all series, filtering to those that are active, and render each using its series type methods.

what do you think?

**Comment by zmaril** [comment]
I've started a transition over to moving away from renderers. It can be seen here: 
https://github.com/activecell/tactile/compare/renderers#L1R71

This recreates the renderers each time render is called on the main chart. The overhead isn't noticeable at this point and it should let us modify the chart and let us see changes propagate into the renderers. Since each renderer is defined as a class, it could take a large amount of refactoring to have each renderer use a static render method. It is doable, but I didn't want to start such a big change when we were going for stability. 

If it looks right to you, I'll merge it into master and we can stop thinking about renderers for a while.
