### ISSUE TITLE
setsize not handling null values properly

### ISSUE THREAD

**Issue by adamrneary** [adamrneary/tactile#27]
in activecell i have had to add heigh and width to the defaults as follows:

``` coffeescript
  initialize: (options) ->
    defaults =
      element: @el
      height: 400
      width: 730
```

if i don't it takes height and width to be 0. in the tactile code, it seems to be trying to check whether there is a passed height/width, but it does not seem to be functioning correctly.

**Comment by zmaril** [comment]
Added in defaults: 
https://github.com/activecell/tactile/commit/67750db0149a7f6e0cefc1761ca628b1ea2727c3

What is happening is that setSize is picking out `this.el` and using the width and height of that as backups: 
https://github.com/activecell/tactile/blob/master/src/js/models/chart.coffee#L146

I can only guess why that is being done is that if you are updating only one dimension, you would want the other one to remain constant.
