### ISSUE TITLE
improve tooltips

### ISSUE THREAD

**Issue by adamrneary** [adamrneary/tactile#28]
as of 12/21 we're 99% there with tooltips. the code could use a bit of a refactor, but more importantly the tooltip is following the mouse rather than being anchored to the node itself.

without knowing the code very well, i can observe that we constrain the tooltip horizontally (it doesn't follow the mouse left and right), so we need a similar enough approach to intercept the y value and make sure it's taking the current node y rather than the mouse y during drag.

**Comment by ksarna** [comment]
Tooltip is now anchored but the node value is not refreshed continuously.
