### ISSUE TITLE
axes

### ISSUE THREAD

**Issue by adamrneary** [adamrneary/tactile#3]
d3 provides https://github.com/mbostock/d3/wiki/SVG-Axes with most of the functionality we need, so we just want to wrap this as minimally as possible

most of our charts have a linear y-axis on the left and a time series x-axis on the bottom, but we also need to be able to have a discrete list for the x-axis, and we will need y2 on the right. 

series should know which y-axis they are plotting against if there are multiple.

**Comment by adamrneary** [comment]
@zmaril I think there's a gap in the way we've implemented the x-axis relative to the timeframe variable in tactile:

```
# this trims data down to the range that is currently viewed. 
# See range_slider for a clue how it's used
_slice: (d) => (@timeframe[0] <= d.x <= @timeframe[1])
```

see http://bl.ocks.org/1166403

on an update to the timeframe, we want it to transition the portion of the x-axis displayed, whereas currently it seems to be flashing the update in place and then animating the series up and down (rather than left to right), which violates object constancy:  http://bost.ocks.org/mike/constancy/

**Comment by zmaril** [comment]
This should be fixed now: 
http://tactile-showcase.herokuapp.com/#sliding-timeframe
