### ISSUE TITLE
area series

### ISSUE THREAD

**Issue by adamrneary** [adamrneary/tactile#9]
Basically exactly the same as the line chart, built with a d3 path, but the area under the line is colored the same as the line (but with partial opacity, see http://cl.ly/image/0F290R131w02)

Editable by dragging the nodes.

**Comment by ksarna** [comment]
Wait! Forgot about the opacity ;)

TODO:
• turn on opacity
• make an example with > 2 series on a single chart

**Comment by ksarna** [comment]
done!

**Comment by adamrneary** [comment]
let's include the time slider once complete on this chart, as well, so that we know it works.

**Comment by adamrneary** [comment]
Also, this series need to be editable.
